<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1IPLMO6\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1IPLMO6/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1IPLMO6.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container1IPLMO6\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container1IPLMO6\App_KernelDevDebugContainer([
    'container.build_hash' => '1IPLMO6',
    'container.build_id' => '4e4d90fb',
    'container.build_time' => 1669038273,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1IPLMO6');
