<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0EXy5JT\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0EXy5JT/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container0EXy5JT.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container0EXy5JT\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container0EXy5JT\App_KernelDevDebugContainer([
    'container.build_hash' => '0EXy5JT',
    'container.build_id' => '440bb5f7',
    'container.build_time' => 1669574044,
], __DIR__.\DIRECTORY_SEPARATOR.'Container0EXy5JT');
